RazorPage/RazorPage/Models/ErrorViewModel.cs
using System;

namespace RazorPage.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RazorPage/RazorPage/Models/Sozler.cs
using Microsoft.AspNetCore.Mvc;
using RazorPage.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPage.Models
{
    public class Sozler
    {
        public int Id { get; set; }
        public string Soz { get; set; }
      
    }
}

RazorPage/RazorPage/Models/Students.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPage.Models
{
    public class Students
    {
        
        public int Id { get; set; }

        [Required]
        [MinLength(3), MaxLength(20)]
        [RegularExpression(@"^[a-zA-ZÖöıİşçÇğĞÜüŞ''-'\s]+$",
         ErrorMessage = "İsim alanına Rakam ve özel karakter girilemez.")]
        public string FirstName { get; set; }

        [Required]
        [MinLength(3), MaxLength(20)]
        [RegularExpression(@"^[a-zA-ZÖöıİşçÇğĞÜüŞ''-'\s]+$",
        ErrorMessage = "İsim alanına Rakam ve özel karakter girilemez.")]
        public string LastName { get; set; }

        [Required]
        [MinLength(3), MaxLength(20)]
        [RegularExpression(@"^[a-zA-ZÖöıİşçÇğĞÜüŞ0-9''-'\s]+$",
        ErrorMessage = "İsim alanına Rakam ve özel karakter girilemez.")]
        public string UserName { get; set; }


        [Required(ErrorMessage = "Şifre alanı boş olamaz.")]
        [MinLength(7), MaxLength(20)]
        [DataType(DataType.Password)]
        [RegularExpression(@"^[a-zA-Z0-9İıöÖüÜçÇğĞşŞ]{7,20}$", ErrorMessage = "En az 7, en fazla 20 karakter girilebilir Özel karakter girilemez!")]
        public string Password { get; set; }



        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Şifreler eşleşmiyor.")]
        [StringLength(20, ErrorMessage = "En az 7, en fazla 20 karakter girilebilir Özel karakter girilemez!", MinimumLength = 7)]
        public string ConfirmPassword { get; set; }


        [RegularExpression(@"^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Not a valid email")]
        public string Email { get; set; }
       
    }
}

RazorPage/RazorPage/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RazorPage.Models;

namespace RazorPage.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RazorPage/RazorPage/Pages/Student/Student.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPage.Models;

namespace RazorPage
{
    public class StudentModel : PageModel
    {

        public List<Students> students { get; private set; }

        public void OnGet()
        {

            students = new List<Students> {
                new Students()
           {
               Id = 1,
               FirstName = "Fİrst Name 1",
               LastName = "Last Name 1",
               UserName = "User Name 1",
               Password = "Password 1",
               Email = "User1@gmail.com"
           },
                new Students()
                {
                    Id = 2,
                    FirstName = "Fİrst Name 2",
                    LastName = "Last Name 2",
                    UserName = "User Name 2",
                    Password = "Password 2",
                    Email = "User2@gmail.com"
                },
                new Students()
                {
                    Id = 3,
                    FirstName = "Fİrst Name 3",
                    LastName = "Last Name 3",
                    UserName = "User Name 3",
                    Password = "Password 3",
                    Email = "User3@gmail.com"
                }
                };
        }
        [BindProperty]
        public Students Students { get; set; }
        public IActionResult OnPostAaa()
        {
            students = new List<Students> {
                new Students()
           {
               Id = 1,
               FirstName = "Fİrst Name 1",
               LastName = "Last Name 1",
               UserName = "User Name 1",
               Password = "Password 1",
               Email = "User1@gmail.com"
           },
                new Students()
                {
                    Id = 2,
                    FirstName = "Fİrst Name 2",
                    LastName = "Last Name 2",
                    UserName = "User Name 2",
                    Password = "Password 2",
                    Email = "User2@gmail.com"
                },
                new Students()
                {
                    Id = 3,
                    FirstName = "Fİrst Name 3",
                    LastName = "Last Name 3",
                    UserName = "User Name 3",
                    Password = "Password 3",
                    Email = "User3@gmail.com"
                },
                 new Students()
                {
                    Id = 4,
                    FirstName =Students.FirstName,
                    LastName = Students.LastName,
                    UserName = Students.UserName,
                    Password =Students.Password,
                    Email = Students.Email
                }
                };
            return RedirectToPage("/Student/Student");
        }



    }
}

RazorPage/RazorPage/ViewComponents/AaaViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPage.ViewComponents
{
    [ViewComponent]
    public class AaaViewComponent: ViewComponent
    {
        public AaaViewComponent()
        {

        }
        public IViewComponentResult Invoke()
        {
            return View();


        }
    }
}

RazorPage/RazorPage/ViewComponents/SozlerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RazorPage.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPage.ViewComponents
{
    [ViewComponent]
    public class SozlerViewComponent:ViewComponent
    {

        public List<Sozler> sozlers { get; private set; }

        public IViewComponentResult Invoke()
        {

            sozlers = new List<Sozler>()
        {
            new Sozler(){Id= 1 ,Soz = "Hırs başarısızlığın son sığınağıdır. "},
            new Sozler(){Id= 2 ,Soz = "Zihin fukara olunca akıl ukala olurmuş. "},
            new Sozler(){Id= 3 ,Soz = "Seni hayallerine ulaştıracak en önemli şey, cesaretindir. "},
            new Sozler(){Id= 4 ,Soz = "Kod, espiri gibidir. Açıklamak zorundaysanız kötüdür.   Cory House"},
            new Sozler(){Id= 5 ,Soz = "Bedava peynir sadece fare kapanında olur.  Ahmet Şerif İzgören"},
            new Sozler(){Id= 6 ,Soz = "Kod yalan söylemez, yorumlar bazen söyler.    Ron Jeffries "},
        };
            Random random = new Random();
            int num = random.Next(1, sozlers.Count);
       
             var  deg = (from sozler in sozlers where sozler.Id == num select sozler).FirstOrDefault();
       
            return View(deg); 


        }
    }
}

RazorPage/RazorPage/Pages/Student/Student.cshtml
@page
@model RazorPage.StudentModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Student";
    Layout = "_Layout";
}

<h1>Student</h1>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>

    <h3>Products List</h3>
    <table border="1" cellpadding="2" cellspacing="2">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Photo</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
        </tr>
        @foreach (var product in Model.students)
        {
            <tr>
                <td>@product.Id</td>
                <td>@product.FirstName</td>
                <td>@product.LastName"</td>
                <td>@product.UserName</td>
                <td>@product.Password</td>
                <td>@product.Email</td>
            </tr>
        }
    </table>

</body>
</html>
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-page-handler="Aaa">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Students.FirstName" class="control-label"></label>
                <input asp-for="Students.FirstName" class="form-control" />
                <span asp-validation-for="Students.FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Students.LastName" class="control-label"></label>
                <input asp-for="Students.LastName" class="form-control" />
                <span asp-validation-for="Students.LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Students.UserName" class="control-label"></label>
                <input asp-for="Students.UserName" class="form-control" />
                <span asp-validation-for="Students.UserName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Students.Password" class="control-label"></label>
                <input asp-for="Students.Password" class="form-control" />
                <span asp-validation-for="Students.Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Students.ConfirmPassword" class="control-label"></label>

                <input asp-for="Students.ConfirmPassword" class="form-control" />
                <span asp-validation-for="Students.ConfirmPassword" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Students.Email" class="control-label"></label>
                <input asp-for="Students.Email" class="form-control" />
                <span asp-validation-for="Students.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
          
        </form>
    </div>
</div>

<div>
  
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RazorPage/RazorPage/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<div>

</div>

RazorPage/RazorPage/Views/Shared/Components/Aaa/Default.cshtml
<div>Merhaba</div>

RazorPage/RazorPage/Views/Shared/Components/Sozler/Default.cshtml
@model RazorPage.Models.Sozler

<span><i>@Model.Soz</i></span>

RazorPage/RazorPage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RazorPage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RazorPage</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Student">RazorPage</a>
                    </ul>
                </div>
                <div >
                    @await Component.InvokeAsync("Sozler")
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()

        </main>
      
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - RazorPage - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)


</body>
</html>